version: '3.3'
services:
  waas:
    image: plowsof/waas:latest
    restart: on-failure
    container_name: fresh
    volumes:
      - waas-db:/home/app/db
      - waas-wallets:/home/app/wallets
      - waas-static:/home/app/static
      - /proc:/writable_proc
    networks:
      static-network:
        ipv4_address: 172.20.111.2
    expose:
      - 8000
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    environment:
      - waas_RSS_ON=1
      - waas_TITLE="Crowd Funding"
      - waas_INTRO="Welcome to my funding page!"
      - waas_RSS_TITLE="Crypto-Funding Page"
      - waas_RSS_DESC="Help support my projects and running costs"
      - waas_RSS_LINK="https://getwishlisted.xyz" 
      - waas_remote_node_1="nodex.monerujo.io:18081"
      - waas_remote_node_2="node.sethforprivacy.com:18089"
      - waas_remote_node_3="xmr-node-usa-east.cakewallet.com:18081"
      - waas_remote_node_4="electroncash.dk:18089"
      - waas_remote_node_5="node.community.rino.io:18081"
      - waas_remote_node_6="selsta2.featherwallet.net:18081" 
      - waas_remote_node_7="selsta1.featherwallet.net:18081"
      - waas_wow_remote_node_1="eu-west-3.wow.xmr.pm:34568"
      - waas_wow_remote_node_2="wow.bot.tips:34568"
      - waas_wow_remote_node_3="eu-west-4.wow.xmr.pm:34568"
      - waas_wow_remote_node_4="wownero.fyi:34568"
      - waas_wow_remote_node_5="nimiq.wangyp.eu.org:34568"
      - waas_mainnet=1
volumes:
  waas-db:
  waas-wallets:
  waas-static:
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
