version: '3.3'
services:
  waas:
    image: plowsof/waas4rucknium-testnet:beta-4
    container_name: fresh
    volumes:
      - waas-db:/home/app/db
      - waas-wallets:/home/app/wallets
      - waas-static:/home/app/static
      - waas-electrum:/home/.electrum
      - waas-electron:/home/.electron-cash
      - ./ssl:/home/app/ssl
      - /proc:/writable_proc
      - waas-cron:/etc/cron.d/
    expose:
      - 8000
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined 
volumes:
  waas-db:
  waas-wallets:
  waas-static:
  waas-electrum:
  waas-electron:
  waas-cron:
