name: WaaS Request
description: File a bug report
title: "[WaaS Request]: "
body:
   - type: markdown
    attributes:
      value: |
        I'm doing a beta test of the WaaS and would like to host donation pages for developers that are being held back by sub-par hardware or lack of disk space for example. Fill the form out below, let us know who you are / what you're doing and how people can help you. 
  - type: textarea
    id: about
    attributes:
      label: Who are you?
      description: Introduce yourself, what you've been doing and what you plan on doing
      placeholder: Hello world... i've done some things, and now i have an idea, and i need to compile monero from source, but my computer is a potato, I've seen a nice laptop on craigslist for $300 please help me thanks.
    validations:
      required: true
  - type: input
    id: xmr_vk
    attributes:
      label: Monero Secret View Key
   - type: input
    id: xmr_pa
    attributes:
      label: Monero Primary Address
  - type: input
    id: wow_vk
    attributes:
      label: WOWnero Secret View Key
   - type: input
    id: wow_pa
    attributes:
      label: WOWnero Primary Address
   - type: input
    id: bch_vk
    attributes:
      label: Bitcoin Cash Master View Key
   - type: input
    id: btc_vk
    attributes:
      label: Bitcoin Master View Key
