name: WaaS Request
description: Get a page @ p2pcrowd.fund
title: "[WaaS Request]: "
labels: ["WaaS"]
assignees:
  - plowsof
body:
  - type: markdown
    attributes:
      value: |
        I am going to host WaaS pages for developers/contributors who are suffering from sub-par hardware and require some funding to increase their producitivity. 
        Ideally some way of proving the equipment was purchased after being funded.
        Also if you leave any crypto's blank, ill have to create the wallet for you and pass you the keys (dont make me feel sus)
  - type: textarea
    id: title
    attributes:
      label: Title
      placeholder: John Does Funding Page
  - type: textarea
    id: intro
    attributes:
      label: inrto
      description: Short introduction about yourself, github link / what do you do?
    validations:
      required: true
  - type: textarea
    id: wishes
    attributes:
      label: What do you need donations for?
      description: Describe your wish(es), how will they benefit you, and how much $ they require?
    validations:
      required: true
  - type: input
    id: xmr_svk
    attributes:
      label: Monero Secret View Key
  - type: input
    id: xmr_pa
    attributes:
      label: Monero Primary Address
  - type: input
    id: wow_svk
    attributes:
      label: Wownero Secret View Key
  - type: input
    id: wow_pa
    attributes:
      label: Wownero Primary Address
  - type: input
    id: bch_mvk
    attributes:
      label: Bitcoin Cash Master Public Key 
      description: In Electron-cash -> Wallet -> Information
      placeholder: xpub....
  - type: input
    id: btc_mvk
    attributes:
      label: Bitcoin Master Public Key
      description: In Electrum -> Wallet -> Information
      placeholder: zpub....
