name: WaaS Request
description: File a bug report
title: "[WaaS Request]: "
labels: ["WaaS"]
assignees:
  - plowsof
body:
  - type: markdown
    attributes:
      value: |
        I am going to host WaaS pages for developers who are suffering from sub-par hardware and require some funding to increase their producitivity.  
  - type: textarea
    id: intro
    attributes:
      label: Who are you?
      description: Introduce yourself, what have you done / what are you doing now?
    validations:
      required: true
  - type: textarea
    id: wishes
    attributes:
      label: What do you need donations for?
      description: Describe your wish(es), how will they benefit you, and how much $ will they cost?
    validations:
      required: true
  - type: input
    id: xmr_svk
    attributes:
      label: Monero Secret View Key
  - type: input
    id: xmr_pa
    attributes:
      label: Monero Primary Address
  - type: input
    id: wow_svk
    attributes:
      label: Wownero Secret View Key
  - type: input
    id: wow_pa
    attributes:
      label: Wownero Primary Address
  - type: input
    id: bch_mvk
    attributes:
      label: Bitcoin Cash Master View Key 
  - type: input
    id: btc_mvk
    attributes:
      label: Bitcoin Master View Key  
