name: WaaS Request
description: Get a page @ p2pcrowd.fund
title: "[WaaS Request]: "
labels: ["WaaS"]
assignees:
  - plowsof
body:
  - type: markdown
    attributes:
      value: |
        I am going to host WaaS pages for developers/contributors who are suffering from sub-par hardware and require some funding to increase their producitivity. Ideally some way of proving the equipment was purchased after being funded.  
  - type: textarea
    id: intro
    attributes:
      label: Who are you?
      description: Introduce yourself, what have you done / what are you doing now?
    validations:
      required: true
  - type: textarea
    id: wishes
    attributes:
      label: What do you need donations for?
      description: Describe your wish(es), how will they benefit you, and how much $ will they cost?
    validations:
      required: true
  - type: input
    id: xmr_svk
    attributes:
      label: Monero Secret View Key
  - type: input
    id: xmr_pa
    attributes:
      label: Monero Primary Address
  - type: input
    id: wow_svk
    attributes:
      label: Wownero Secret View Key
  - type: input
    id: wow_pa
    attributes:
      label: Wownero Primary Address
  - type: input
    id: bch_mvk
    attributes:
      label: Bitcoin Cash Master Public Key 
      description: In Electron-cash -> Wallet -> Information
      placeholder: xpub....
  - type: input
    id: btc_mvk
    attributes:
      label: Bitcoin Master Public Key
      description: In Electrum -> Wallet -> Information
      placeholder: zpub....
