name: WaaS Request
description: File a bug report
title: "[WaaS Request]: "
labels: ["WaaS"]
assignees:
  - plowsof
body:
  - type: markdown
    attributes:
      value: |
        Hello world!
  - type: input
    id: xmr_svk
    attributes:
      label: Monero Secret View Key
  - type: input
    id: xmr_pa
    attributes:
      label: Monero Primary Address
  - type: input
    id: bch_mvk
    attributes:
      label: Bitcoin Cash Master View Key 
  - type: input
    id: btc_mvk
    attributes:
      label: Bitcoin Master View Key       
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
